kind: pipeline
name: build
type: docker

steps:
- name: build
  image: plugins/docker
  pull: if-not-exists
  settings:
    pull: false
    pull_image: false
    #cache_from: node:14
    tags: ${DRONE_COMMIT_BRANCH}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo:
      from_secret: docker_repo
    registry:
      from_secret: docker_registry
  when:
    branch:
      include:
        - master
        - develop
        - deinwal21

- name: notify
  image: drillster/drone-email
  settings:
    host:
      from_secret: drone_mail_host
    username:
      from_secret: drone_mail_user
    password:
      from_secret: drone_mail_password
    from:
      from_secret: drone_mail_noreply
  when:
    status: [ success, failure ]
