#kind: pipeline
#name: lint
#type: docker
#
#steps:
#- name: lint
#  image: node:lts-slim
#  commands:
#    - npm ci --cache .npm-cache --prefer-offline
#    - npm run lint
#
#---

kind: pipeline
name: build
type: docker

# only build on master and develop
trigger:
  branch:
    - master
    - develop

steps:
#- name: lint
#  image: node:lts-slim
#  commands:
#    - npm ci --cache .npm-cache --prefer-offline
#    - npm run lint
- name: build
  image: plugins/docker
  pull: if-not-exists
  #image: node:lts-slim
  #commands:
  #  - npm ci --cache .npm-cache --prefer-offline
  #  - npm run build --prod
  settings:
    pull: false
    pull_image: false
    #cache_from: node:14
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: docker-registry.codeahoi.de/wahlhelfer/wahlberater
    registry: docker-registry.codeahoi.de
