kind: pipeline
name: build
type: docker

# only build on master and develop
trigger:
  branch:
    - master
    - develop

steps:
- name: build
  image: plugins/docker
  pull: if-not-exists
  settings:
    pull: false
    pull_image: false
    #cache_from: node:14
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: docker-registry.codeahoi.de/wahlhelfer/wahlberater
    registry: docker-registry.codeahoi.de
