kind: pipeline
name: lint
type: docker

steps:
- name: lint
  image: node:lts-slim
  commands:
    - npm ci --cache .npm-cache --prefer-offline
    - npm run lint

---

kind: pipeline
name: build
type: docker

# only build on master and develop
trigger:
  branch:
    - master
    - develop

steps:
- name: build
  image: node:lts-slim
  commands:
    - npm ci --cache .npm-cache --prefer-offline
    - npm run build --prod
